[package]
org = "dell"
name = "data_service"
version = "0.1.0"
distribution = "2201.1.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "C:\\Program Files (x86)\\MySQL\\Connector J 8.0\\mysql-connector-java-8.0.30.jar"